# Generated by Django 2.2.2 on 2019-06-17 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scheduling',
            new_name='Appointment',
        ),
    ]
