# Generated by Django 2.2.2 on 2019-06-17 08:59

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduling',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Africa/Nairobi'),
        ),
    ]
