# Generated by Django 2.2.2 on 2019-06-18 08:28

from django.db import migrations
import timezone_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0002_auto_20190617_0606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='time_zone',
            field=timezone_field.fields.TimeZoneField(default='Africa/Nairobi'),
        ),
    ]
