# Generated by Django 2.2.2 on 2019-06-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0003_adduser_emailgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='phone',
            field=models.IntegerField(null=True),
        ),
    ]
