# Generated by Django 2.2.2 on 2019-06-20 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_schedulingemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedulingemails',
            name='email',
            field=models.EmailField(max_length=40),
        ),
    ]
