# Generated by Django 2.2.2 on 2019-06-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('automation', '0004_auto_20190617_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adduser',
            name='phone',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
